theme: jekyll-theme-minimal
title: Unidos
description: Unidos é um aplicativo criado com o objetivo de facilitar e estimular doações para ONGs aonde o doador acumula pontos a cada doação e pode resgatá-los como rescompensas.
